version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            # We want to compare the CI build output against the checked-in build output
            # However, some type declarations may differ between minor compiler versions due to a typescript issue: https://github.com/microsoft/TypeScript/issues/17944
            # Therefore we exclude type declarations from the 'git diff' comparison
            # When the typescript issue is resolved, we can just use 'git diff'
            - run: if [[ $(git diff -- . ':(exclude)**/*.d.ts') ]]; then echo "Build output does not match checked-in assets"; git diff -- . ':(exclude)**/*.d.ts'; exit 1; fi;
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test